config/routes.rb
Rails.application.routes.draw do
  resources :avaliacaos
  resources :atividades
  resources :disciplinas
  resources :alunos
  resources :turmas
  root 'pages#home'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/disciplina.rb
class Disciplina < ApplicationRecord
  belongs_to :turma

  validates :nome, presence: true , uniqueness: true
  validates :ano_letivo, presence: true, comparison: {greater_than_or_equal_to: 2020}

  has_many :atividades
  has_many :alunos, through: :turma
end

app/controllers/disciplinas_controller.rb
class DisciplinasController < ApplicationController
  before_action :set_disciplina, only: %i[ show edit update destroy ]

  # GET /disciplinas or /disciplinas.json
  def index
    @disciplinas = Disciplina.all
  end

  # GET /disciplinas/1 or /disciplinas/1.json
  def show
  end

  # GET /disciplinas/new
  def new
    @disciplina = Disciplina.new
  end

  # GET /disciplinas/1/edit
  def edit
  end

  # POST /disciplinas or /disciplinas.json
  def create
    @disciplina = Disciplina.new(disciplina_params)

    respond_to do |format|
      if @disciplina.save
        format.html { redirect_to disciplina_url(@disciplina), notice: "Disciplina was successfully created." }
        format.json { render :show, status: :created, location: @disciplina }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @disciplina.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /disciplinas/1 or /disciplinas/1.json
  def update
    respond_to do |format|
      if @disciplina.update(disciplina_params)
        format.html { redirect_to disciplina_url(@disciplina), notice: "Disciplina was successfully updated." }
        format.json { render :show, status: :ok, location: @disciplina }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @disciplina.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /disciplinas/1 or /disciplinas/1.json
  def destroy
    @disciplina.destroy

    respond_to do |format|
      format.html { redirect_to disciplinas_url, notice: "Disciplina was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_disciplina
      @disciplina = Disciplina.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def disciplina_params
      params.require(:disciplina).permit(:nome, :ano_letivo, :turma_id)
    end
end

app/helpers/disciplinas_helper.rb
module DisciplinasHelper
end

app/views/disciplinas/_disciplina.html.erb
<div id="<%= dom_id disciplina %>">
  <p>
    <strong>Nome:</strong>
    <%= disciplina.nome %>
  </p>

  <p>
    <strong>Ano letivo:</strong>
    <%= disciplina.ano_letivo %>
  </p>

  <p>
    <strong>Turma:</strong>
    <%= disciplina.turma.nome %>
  </p>

</div>

app/views/disciplinas/_form.html.erb
<%= form_with(model: disciplina) do |form| %>
  <% if disciplina.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(disciplina.errors.count, "error") %> prohibited this disciplina from being saved:</h2>

      <ul>
        <% disciplina.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :ano_letivo, style: "display: block" %>
    <%= form.number_field :ano_letivo %>
  </div>

  <div class="field">
    <%= form.label :turma_id %>
    <%= form.collection_select(:turma_id, Turma.all, :id, :nome,{:selected => @disciplina.turma_id})%>
  </div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/disciplinas/edit.html.erb
<h1>Editing disciplina</h1>

<%= render "form", disciplina: @disciplina %>

<br>

<div>
  <%= link_to "Show this disciplina", @disciplina %> |
  <%= link_to "Back to disciplinas", disciplinas_path %>
</div>

app/views/disciplinas/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Disciplinas</h1>

<div id="disciplinas">
  <% @disciplinas.each do |disciplina| %>
    <%= render disciplina %>
    <p>
      <%= link_to "Show this disciplina", disciplina %>
    </p>
  <% end %>
</div>

<%= link_to "New disciplina", new_disciplina_path %>

app/views/disciplinas/new.html.erb
<h1>New disciplina</h1>

<%= render "form", disciplina: @disciplina %>

<br>

<div>
  <%= link_to "Back to disciplinas", disciplinas_path %>
</div>

app/views/disciplinas/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @disciplina %>

<div>
  <%= link_to "Edit this disciplina", edit_disciplina_path(@disciplina) %> |
  <%= link_to "Back to disciplinas", disciplinas_path %>

  <%= button_to "Destroy this disciplina", @disciplina, method: :delete %>
</div>