config/routes.rb
Rails.application.routes.draw do
  resources :avaliacaos
  resources :atividades
  resources :disciplinas
  resources :alunos
  resources :turmas
  root 'pages#home'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/atividade.rb
class Atividade < ApplicationRecord
  belongs_to :disciplina

  validates :titulo, presence: true, length: {minimum: 5, too_short: "tamanho minimo 5 caracteres", maximum: 20, too_long: "tamanho maximo de 20 caracteres"}
  validates :descricao, presence: true
  validates :bimestre, presence: true, numericality: true
  validates :data, presence: true

  has_one :aluno
  has_one :avaliacao
end

app/controllers/atividades_controller.rb
class AtividadesController < ApplicationController
  before_action :set_atividade, only: %i[ show edit update destroy ]

  # GET /atividades or /atividades.json
  def index
    @atividades = Atividade.all
  end

  # GET /atividades/1 or /atividades/1.json
  def show
  end

  # GET /atividades/new
  def new
    @atividade = Atividade.new
  end

  # GET /atividades/1/edit
  def edit
  end

  # POST /atividades or /atividades.json
  def create
    @atividade = Atividade.new(atividade_params)

    respond_to do |format|
      if @atividade.save
        format.html { redirect_to atividade_url(@atividade), notice: "Atividade was successfully created." }
        format.json { render :show, status: :created, location: @atividade }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @atividade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /atividades/1 or /atividades/1.json
  def update
    respond_to do |format|
      if @atividade.update(atividade_params)
        format.html { redirect_to atividade_url(@atividade), notice: "Atividade was successfully updated." }
        format.json { render :show, status: :ok, location: @atividade }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @atividade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /atividades/1 or /atividades/1.json
  def destroy
    @atividade.destroy

    respond_to do |format|
      format.html { redirect_to atividades_url, notice: "Atividade was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_atividade
      @atividade = Atividade.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def atividade_params
      params.require(:atividade).permit(:titulo, :bimestre, :descricao, :data, :disciplina_id)
    end
end

app/helpers/atividades_helper.rb
module AtividadesHelper
end

app/views/atividades/_atividade.html.erb
<div id="<%= dom_id atividade %>">
  <p>
    <strong>Titulo:</strong>
    <%= atividade.titulo %>
  </p>

  <p>
    <strong>Bimestre:</strong>
    <%= atividade.bimestre %>
  </p>

  <p>
    <strong>Descricao:</strong>
    <%= atividade.descricao %>
  </p>

  <p>
    <strong>Data:</strong>
    <%= atividade.data %>
  </p>

  <p>
    <strong>Disciplina:</strong>
    <%= atividade.disciplina_id %>
  </p>

</div>

app/views/atividades/_form.html.erb
<%= form_with(model: atividade) do |form| %>
  <% if atividade.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(atividade.errors.count, "error") %> prohibited this atividade from being saved:</h2>

      <ul>
        <% atividade.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :titulo, style: "display: block" %>
    <%= form.text_field :titulo %>
  </div>

  <div>
    <%= form.label :bimestre, style: "display: block" %>
    <%= form.number_field :bimestre %>
  </div>

  <div>
    <%= form.label :descricao, style: "display: block" %>
    <%= form.text_field :descricao %>
  </div>

  <div>
    <%= form.label :data, style: "display: block" %>
    <%= form.date_field :data %>
  </div>

  <div class="field">
    <%= form.label :disciplina_id %>
    <%= form.collection_select(:disciplina_id, Disciplina.all, :id, :nome,{:selected => @atividade.disciplina_id})%>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/atividades/edit.html.erb
<h1>Editing atividade</h1>

<%= render "form", atividade: @atividade %>

<br>

<div>
  <%= link_to "Show this atividade", @atividade %> |
  <%= link_to "Back to atividades", atividades_path %>
</div>

app/views/atividades/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Atividades</h1>

<div id="atividades">
  <% @atividades.each do |atividade| %>
    <%= render atividade %>
    <p>
      <%= link_to "Show this atividade", atividade %>
    </p>
  <% end %>
</div>

<%= link_to "New atividade", new_atividade_path %>

app/views/atividades/new.html.erb
<h1>New atividade</h1>

<%= render "form", atividade: @atividade %>

<br>

<div>
  <%= link_to "Back to atividades", atividades_path %>
</div>

app/views/atividades/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @atividade %>

<div>
  <%= link_to "Edit this atividade", edit_atividade_path(@atividade) %> |
  <%= link_to "Back to atividades", atividades_path %>

  <%= button_to "Destroy this atividade", @atividade, method: :delete %>
</div>