config/routes.rb
Rails.application.routes.draw do
  resources :avaliacaos
  resources :atividades
  resources :disciplinas
  resources :alunos
  resources :turmas
  root 'pages#home'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/avaliacao.rb
class Avaliacao < ApplicationRecord
  belongs_to :aluno
  belongs_to :atividade

  validates :pontos, presence:true, numericality: { in: 0..10 }

end

app/controllers/avaliacaos_controller.rb
class AvaliacaosController < ApplicationController
  before_action :set_avaliacao, only: %i[ show edit update destroy ]

  # GET /avaliacaos or /avaliacaos.json
  def index
    @avaliacaos = Avaliacao.all
  end

  # GET /avaliacaos/1 or /avaliacaos/1.json
  def show
  end

  # GET /avaliacaos/new
  def new
    @avaliacao = Avaliacao.new
  end

  # GET /avaliacaos/1/edit
  def edit
  end

  # POST /avaliacaos or /avaliacaos.json
  def create
    @avaliacao = Avaliacao.new(avaliacao_params)

    respond_to do |format|
      if @avaliacao.save
        format.html { redirect_to avaliacao_url(@avaliacao), notice: "Avaliacao was successfully created." }
        format.json { render :show, status: :created, location: @avaliacao }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @avaliacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /avaliacaos/1 or /avaliacaos/1.json
  def update
    respond_to do |format|
      if @avaliacao.update(avaliacao_params)
        format.html { redirect_to avaliacao_url(@avaliacao), notice: "Avaliacao was successfully updated." }
        format.json { render :show, status: :ok, location: @avaliacao }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @avaliacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /avaliacaos/1 or /avaliacaos/1.json
  def destroy
    @avaliacao.destroy

    respond_to do |format|
      format.html { redirect_to avaliacaos_url, notice: "Avaliacao was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_avaliacao
      @avaliacao = Avaliacao.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def avaliacao_params
      params.require(:avaliacao).permit(:pontos, :observacoes, :aluno_id, :atividade_id)
    end
end

app/helpers/avaliacaos_helper.rb
module AvaliacaosHelper
end

app/views/avaliacaos/_avaliacao.html.erb
<div id="<%= dom_id avaliacao %>">
  <p>
    <strong>Pontos:</strong>
    <%= avaliacao.pontos %>
  </p>

  <p>
    <strong>Observacoes:</strong>
    <%= avaliacao.observacoes %>
  </p>

  <p>
    <strong>Aluno:</strong>
    <%= avaliacao.aluno_id %>
  </p>

  <p>
    <strong>Atividade:</strong>
    <%= avaliacao.atividade_id %>
  </p>

</div>

app/views/avaliacaos/_form.html.erb
<%= form_with(model: avaliacao) do |form| %>
  <% if avaliacao.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(avaliacao.errors.count, "error") %> prohibited this avaliacao from being saved:</h2>

      <ul>
        <% avaliacao.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :pontos, style: "display: block" %>
    <%= form.number_field :pontos %>
  </div>

  <div>
    <%= form.label :observacoes, style: "display: block" %>
    <%= form.text_field :observacoes %>
  </div>

  <div class="field">
    <%= form.label :aluno_id %>
    <%= form.collection_select(:aluno_id, Aluno.all, :id, :nome,{:selected => @avaliacao.aluno_id})%>
  </div>
>

  <div class="field">
    <%= form.label :atividade_id %>
    <%= form.collection_select(:atividade_id, Atividade.all, :id, :titulo,{:selected => @avaliacao.atividade_id})%>
  </div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/avaliacaos/edit.html.erb
<h1>Editing avaliacao</h1>

<%= render "form", avaliacao: @avaliacao %>

<br>

<div>
  <%= link_to "Show this avaliacao", @avaliacao %> |
  <%= link_to "Back to avaliacaos", avaliacaos_path %>
</div>

app/views/avaliacaos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Avaliacaos</h1>

<div id="avaliacaos">
  <% @avaliacaos.each do |avaliacao| %>
    <%= render avaliacao %>
    <p>
      <%= link_to "Show this avaliacao", avaliacao %>
    </p>
  <% end %>
</div>

<%= link_to "New avaliacao", new_avaliacao_path %>

app/views/avaliacaos/new.html.erb
<h1>New avaliacao</h1>

<%= render "form", avaliacao: @avaliacao %>

<br>

<div>
  <%= link_to "Back to avaliacaos", avaliacaos_path %>
</div>

app/views/avaliacaos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @avaliacao %>

<div>
  <%= link_to "Edit this avaliacao", edit_avaliacao_path(@avaliacao) %> |
  <%= link_to "Back to avaliacaos", avaliacaos_path %>

  <%= button_to "Destroy this avaliacao", @avaliacao, method: :delete %>
</div>